version: "3.8"
services: # Define los servicios que componen la aplicación
  db_postgres:  # Define
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-sql:/docker-entrypoint-initdb.d # Carpeta con scripts sql
    networks:
      - mynetwork

  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pg_admin
    restart: always
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - mynetwork

  nginx_web:
    image: nginx:latest
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      #- ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - mynetwork

  db_mysql:
    image: mysql:latest
    container_name: mysql_db
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork
  
networks:
  mynetwork:

volumes:
  pgadmin_data:
  pg_data:
  db_data:
  portainer_data: